// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-link.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/profile.ts
var PROFILE = {
  name: "Anas Ayman",
  headline: "Personal landing page",
  siteUrl: "https://anasayman.lovable.app"
};
var PROFILE_LINKS = [
  { platform: "Instagram", handle: "@anasaymah", url: "https://www.instagram.com/anasaymah", kind: "social" },
  { platform: "TikTok", handle: "@anasaymah", url: "https://www.tiktok.com/@anasaymah", kind: "social" },
  { platform: "YouTube", handle: "@AnasAymah", url: "https://www.youtube.com/@AnasAymah", kind: "social" },
  { platform: "Facebook", handle: "Anas Ayman", url: "https://www.facebook.com/anasaymah", kind: "social" },
  { platform: "LinkedIn", handle: "in/anasayman", url: "https://linkedin.com/in/anasayman", kind: "social" },
  { platform: "Threads", handle: "@anasaymah", url: "https://www.threads.net/@anasaymah", kind: "social" },
  { platform: "GitHub", handle: "@anasaymah", url: "https://github.com/anasaymah", kind: "social" },
  { platform: "WhatsApp", handle: "Message me", url: "https://wa.me/201143730504", kind: "contact" }
];

// src/lib/mcp/tools/get-link.ts
var get_link_default = defineTool({
  name: "get_link",
  title: "Get a profile link",
  description: "Get the public URL and handle for one platform (e.g. instagram, youtube, whatsapp).",
  inputSchema: {
    platform: z.string().min(1).describe("Platform name, case-insensitive (e.g. 'instagram').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ platform }) => {
    const needle = platform.trim().toLowerCase();
    const link = PROFILE_LINKS.find((l) => l.platform.toLowerCase() === needle);
    if (!link) {
      throw new ToolError(
        `Unknown platform "${platform}". Available: ${PROFILE_LINKS.map((l) => l.platform).join(", ")}`
      );
    }
    return {
      content: [{ type: "text", text: `${link.platform} (${link.handle}): ${link.url}` }],
      structuredContent: { link }
    };
  }
});

// src/lib/mcp/tools/get-profile.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_profile_default = defineTool2({
  name: "get_profile",
  title: "Get profile summary",
  description: "Get a summary of the public landing page: owner name, headline, site URL, and link count.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const summary = {
      ...PROFILE,
      linkCount: PROFILE_LINKS.length,
      platforms: PROFILE_LINKS.map((l) => l.platform)
    };
    return {
      content: [
        {
          type: "text",
          text: `${summary.name} \u2014 ${summary.headline}
${summary.siteUrl}
Platforms: ${summary.platforms.join(", ")}`
        }
      ],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/list-links.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_links_default = defineTool3({
  name: "list_links",
  title: "List profile links",
  description: "List the public profile links shown on the landing page (social profiles and contact links).",
  inputSchema: {
    kind: z2.enum(["all", "social", "contact"]).default("all").describe("Filter links by kind. Defaults to all.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ kind }) => {
    const links = kind === "all" ? PROFILE_LINKS : PROFILE_LINKS.filter((l) => l.kind === kind);
    return {
      content: [
        {
          type: "text",
          text: links.map((l) => `${l.platform} (${l.handle}): ${l.url}`).join("\n")
        }
      ],
      structuredContent: { links }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "landing-page-builder",
  title: "Landing Page Builder",
  version: "0.1.0",
  instructions: "Read-only tools for the public Anas Ayman landing page. Use `get_profile` for an overview, `list_links` to list all public profile links, and `get_link` to resolve one platform's URL.",
  tools: [get_profile_default, list_links_default, get_link_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
